[package]
# Package names are always "SCOPE/NAME"
# They can include lowercase letters, numbers, and dashes.
name = "cosinewaves/loader"

# Descriptions are free-form. These will be used as part of package listings
# and search results.
description = "A lightweight, lifecycle-aware module loader for Roblox."

# Versions follow Semantic Versioning.
# https://semver.org/
version = "1.2.1"

# Contains an SPDX License Expression.
# Licenses are required for publishing code to public registries.
license = "MIT OR Apache-2.0"

# The author list is a free-form list, but conventionally contains names and
# email addresses.
authors = ["cosinewaves"]

# Packages belong to a "realm", which helps prevent using code in the wrong
# context. For now, we have "server" and "shared" realms.
# The server realm should only be used for packages which shouldn't be replicated.
realm = "shared"

# Wally supports multiple registries.
# This feature can be used to have split public/private registries to
# keep internal code private and isolated.
registry = "https://github.com/upliftgames/wally-index"

# Wally will display this link on the package's page on wally.run.
# A value should only be set if there is a dedicated website for
# the package other than the source repository. 
homepage = "https://cosinewaves.github.io/loader/"

# Wally will display this link on package's page on wally.run.
# The repository field should be a URL to the source repository for a package.
repository = "https://github.com/cosinewaves/loader"



